### ISSUE TITLE
Getting wifi in ventura installer

### ISSUE THREAD

**Issue by flysqu** [jc-bao/surface-laptop3-ventura#7]
Hi, do you have any tips for getting wifi in the installer (specifically ventura in my case). It boots up fine, keyboard and touchpad works but i dont get any was of connecting to wifi, i saw on the dortania guide that it said something about needing a "macos supported network/wifi solution" for like the installer, any pointers on what that can be? I've hackintoshed my thinkpad before but then i just used ethernet in the installer but dont really have that option now. EDIT: I have tried using my android phone's usb tethering feature on both the usb portn and usb c port but that didnt work

**Comment by jc-bao** [comment]
Hi @flysqu , if you want to use wifi in installer, please consider use `AirportItlwm_v2.3.0_stable_Ventura.kext`
 [here](https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.3.0). You can simplify do that by change the config file since I have include both `airportItlwm` and `Itlwm`. If you want to use mine, you should install `Heliport`. Details can be found in their [doc](https://openintelwireless.github.io/itlwm/).

**Comment by flysqu** [comment]
im now getting wifi in the installer! i just removed itlwm and enabled airportitlwm. Thanks alot for your help!!!!
